/**
 * Script to remove auto-generated PSY numbers from patient records
 * 
 * This script identifies patients with PSY numbers that match the auto-generation pattern
 * (PSY + 4-digit year + 6-digit timestamp) and sets them to NULL.
 * 
 * Patient records are NOT deleted - only the psy_no field is cleared.
 */

const db = require('../config/database');

async function removeAutoGeneratedPSYNumbers() {
  try {
    console.log('🔍 Starting removal of auto-generated PSY numbers...\n');

    // First, identify patients with auto-generated PSY numbers
    // Pattern: PSY + 4 digits (year) + 6 digits (timestamp) = PSY followed by exactly 10 digits
    // Regex pattern: ^PSY\d{4}\d{6}$ = PSY + 4 digits + 6 digits
    const findQuery = `
      SELECT id, name, cr_no, psy_no, created_at
      FROM registered_patient
      WHERE psy_no IS NOT NULL
        AND psy_no ~ '^PSY\\d{10}$'
      ORDER BY created_at DESC
    `;

    console.log('📋 Finding patients with auto-generated PSY numbers...');
    const findResult = await db.query(findQuery);
    const patientsToUpdate = findResult.rows;

    if (patientsToUpdate.length === 0) {
      console.log('✅ No patients found with auto-generated PSY numbers.');
      return;
    }

    console.log(`\n📊 Found ${patientsToUpdate.length} patient(s) with auto-generated PSY numbers:\n`);
    
    // Display summary
    patientsToUpdate.forEach((patient, index) => {
      console.log(`${index + 1}. ID: ${patient.id}, Name: ${patient.name}, CR No: ${patient.cr_no}, PSY No: ${patient.psy_no}`);
    });

    // Confirm before proceeding
    console.log(`\n⚠️  About to set psy_no to NULL for ${patientsToUpdate.length} patient(s).`);
    console.log('   Patient records will NOT be deleted - only PSY numbers will be cleared.\n');

    // Update query - set psy_no to NULL for matching patients
    const updateQuery = `
      UPDATE registered_patient
      SET psy_no = NULL,
          updated_at = CURRENT_TIMESTAMP
      WHERE psy_no IS NOT NULL
        AND psy_no ~ '^PSY\\d{10}$'
      RETURNING id, name, cr_no, psy_no
    `;

    console.log('🔄 Updating patient records...');
    const updateResult = await db.query(updateQuery);
    const updatedPatients = updateResult.rows;

    console.log(`\n✅ Successfully updated ${updatedPatients.length} patient record(s).`);
    console.log('\n📋 Updated patients:');
    updatedPatients.forEach((patient, index) => {
      console.log(`${index + 1}. ID: ${patient.id}, Name: ${patient.name}, CR No: ${patient.cr_no}, PSY No: ${patient.psy_no || 'NULL'}`);
    });

    console.log('\n✨ Process completed successfully!');
    console.log('   All auto-generated PSY numbers have been removed.');
    console.log('   Patient records remain intact.\n');

  } catch (error) {
    console.error('❌ Error removing auto-generated PSY numbers:', error);
    throw error;
  }
}

// Run the script
if (require.main === module) {
  removeAutoGeneratedPSYNumbers()
    .then(() => {
      console.log('Script completed.');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Script failed:', error);
      process.exit(1);
    });
}

module.exports = { removeAutoGeneratedPSYNumbers };
